#!/bin/sh
ssh -i "~/hau-server.pem" ubuntu@13.124.33.144 <<EOF
    cd ~/jenkins-test
    git pull origin production
    npm install -g yarn
    yarn install
    yarn run build
    yarn run start:pm2
    exit
EOF
